apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ultron
  template:
    metadata:
      labels:
        app: ultron
    spec:
      containers:
      - name: ultron
        image: samwang0723/ultron:v1.0.0
        imagePullPolicy: Always
        args: ["--target=concentration"]  # This will override the CMD in the Dockerfile
        env:
        - name: ENV
          value: prod
        - name: PROXY_PASSWD
          valueFrom:
            secretKeyRef:
              name: proxy-secret
              key: passwd
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
